### ISSUE TITLE
'Iterable collections' page issue

### ISSUE THREAD

**Issue by vgazioglu** [dart-lang/site-www#2483] opened 2020-06-13 16:01 UTC
Page URL: https://dart.dev/codelabs/iterables.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/codelabs/iterables.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

![image](https://user-images.githubusercontent.com/61664410/84573281-414e8f80-ada8-11ea-8fdf-90613811aabb.png)

**Comment by kwalrath** [comment] 2020-06-15 21:29
Is the issue that when you go to the Solution tab and press Run, you get an exception?

I think that's a DartPad UI issue, since it runs the code that's in the Dart tab, not the code that's in the Solution tab. (I think that's confusing and should be fixed!) If you copy the code from the Solution tab to the Dart tab, the tests pass.

I'm going to close this as a duplicate of https://github.com/dart-lang/dart-pad/issues/1172. If I misunderstood the problem, please comment to let me know. Thanks, @vgazioglu!

**Closed by kwalrath** 2020-06-15 21:29 UTC
Labels: DartPad
