### ISSUE TITLE
Icons in code editor cover the code underneath

### ISSUE THREAD

**Issue by VarunChilukuri** [dart-lang/site-www#2341] opened 2020-04-11 00:37 UTC
https://dart.dev/codelabs/async-await

In the code editor below the "Part 2: reportLogins()" section, there are two icons that cover the text underneath.  One is a "copy code" button and the other is the "full screen" button. They cover the text underneath (which is just commented code).

![Photo with error](https://user-images.githubusercontent.com/48163435/79031180-07c09480-7b6b-11ea-8edf-0f8d87d059b0.JPG)

**Comment by kwalrath** [comment] 2020-04-13 16:22
Dupe of https://github.com/dart-lang/dart-pad/issues/1381. I'm closing this, but thanks for letting us know that this is still a problem.

**Closed by kwalrath** 2020-04-13 16:22 UTC
