### ISSUE TITLE
"Get the Dart SDK" page has list bullet points on top of the text

### ISSUE THREAD

**Issue by refi64** [dart-lang/site-www#2075] opened 2019-11-07 18:31 UTC
![Screenshot from 2019-11-07 12-26-19](https://user-images.githubusercontent.com/1690697/68416624-7895f780-015a-11ea-88ca-f96fe663fdf9.png)

The bullet points for the channel list somehow got stuck on top of the above text.

**Comment by kwalrath** [comment] 2019-11-07 18:45
Known problem. :( Closing as a duplicate of #2054.

(@refi64, if you have any additional information, #2054 would be a great place to put it.)

**Closed by kwalrath** 2019-11-07 18:45 UTC

**Comment by refi64** [comment] 2019-11-08 02:56
Worth noting I had this appear on Chrome though...

**Comment by kwalrath** [comment] 2019-11-08 18:17
That is definitely worth noting! Which version of Chrome? Can you reproduce it?
