### ISSUE TITLE
Hash links are no longer easily accessible on effective dart. 

### ISSUE THREAD

**Issue by har79** [dart-lang/site-www#9] opened 2016-07-14 16:03 UTC
Previously, hovering over an item title on one of the effective-dart pages, brought up a link icon which linked specifically to that item, e.g., https://www.dartlang.org/guides/language/effective-dart/style#prefer-using-lowercamelcase-for-constant-names. This no longer happens making it harder to link to specific parts of the guide.

Also, when using the links, the page appears the selected item's title under the page's header bar.

**Comment by Sfshaza** [comment] 2016-07-14 23:48
Yes, jmesserly also opened this. We didn't realize that this was so heavily used.

Closing this as a duplicate of https://github.com/dart-lang/site-www/issues/13

**Closed by Sfshaza** 2016-07-14 23:48 UTC
