### ISSUE TITLE
[PAGE ISSUE]: 'A tour of the Dart language'

### ISSUE THREAD

**Issue by mobylin** [dart-lang/site-www#3722] opened 2021-12-10 13:09 UTC
### Page URL

https://dart.dev/guides/language/language-tour

### Page source

https://github.com/dart-lang/site-www/tree/master/src/_guides/language/language-tour.md

### Describe the problem

"For more information about maps, see the generics section and the library tour’s coverage of the Maps API."

the link of "Maps API" is wrong

**Comment by parlough** [comment] 2021-12-10 16:01
Hey @mobylin, thanks for opening an issue. The "Maps API" link seems to lead me to https://dart.dev/guides/libraries/library-tour#maps which is the map section of the library tour. Are you seeing different results or do you expect the link to navigate elsewhere? Let us know. Thanks!

**Comment by parlough** [comment] 2022-01-01 03:40
I will close this issue for now as it seems to be working as intended, but if you have any more information or different expectations, let me know by responding and I can re-open the issue. Thanks again!

**Closed by parlough** 2022-01-01 03:40 UTC
Labels: LanguageTour, bad URL, needs-info, e0-minutes
