### ISSUE TITLE
404 Errors on Customizing Analysis Rules

### ISSUE THREAD

**Issue by timsneath** [dart-lang/site-www#3345] opened 2021-06-18 17:32 UTC
https://github.com/dart-lang/site-www/blob/master/src/_guides/language/analysis-options.md#customizing-analysis-rules

These three links are broken:
<img width="870" alt="image" src="https://user-images.githubusercontent.com/2319867/122597629-7d9e7680-d020-11eb-909d-794a3547634c.png">

I spent a little time trying to find their correct replacements, but I ran out of time, so filing a bug instead.

**Comment by parlough** [comment] 2021-06-18 18:12
Thanks for reporting this, I forgot about these dead links. Duplicate of https://github.com/dart-lang/site-www/issues/3175 which I will work on fixing now.

**Closed by parlough** 2021-06-18 18:12 UTC
Labels: analysis, e0-minutes, links, p1-high
