### ISSUE TITLE
Please document {String|int|bool}.fromEnvironment

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/site-www#404] opened 2017-10-20 21:36 UTC
As I've mentioned in https://github.com/dart-lang/sdk/issues/27585:

> `const String.fromEnvironment('FOO') == Platform.environment['FOO']`

... is not true :(

`fromEnvironment` is an [environment declaration](https://api.dartlang.org/stable/1.24.2/dart-core/String/String.fromEnvironment.html), and is configured at "compile time" (differs depending on the platform what that means).

I'd like to see:

* An example of using this (versus `Platform.environment`, which is `dart:io` only)
* How to use it in the VM, how to use it with Pub/Webdev, how to use it with Flutter

**Comment by matanlurey** [comment] 2017-10-20 21:42
One of the reason I think this is important is that it used in tree-shaking.

For example, you could _optionally_ include a ZipFileEncoder library in a Flutter/Web app:

```dart
import 'package:zip/zip.dart' as zip;

/// Returns a list of files as a single compacted file.
///
/// If `ARCHIVE_FILES_COMPRSSED` is set, uses compression.
List<int> archiveFiles(List<List<int>> files) {
  if (const bool.fromEnvironment('ARCHIVE_FILES_COMPRESSED')) {
    return zip.compressFiles(files);
  }
  return _archiveFilesNoCompression(files);
}
```

**Comment by kwalrath** [comment] 2017-10-23 18:29
Can this be handled in the API reference, or do you think it should also be in the language/library tour?

**Comment by kwalrath** [comment] 2019-01-31 23:55
Related (dupe?): #37

**Comment by parlough** [comment] 2022-10-04 01:14
I'm going to close this as a duplicate of https://github.com/dart-lang/site-www/issues/404. The API docs have been expanded a bit, but we definitely should document this on the site still.

**Closed by parlough** 2022-10-04 01:14 UTC
Labels: needs-info
