### ISSUE TITLE
Getting Started page flowchart has Fl written for Flutter instead of Flutter (typo?)

### ISSUE THREAD

**Issue by maryx** [dart-lang/site-www#472] opened 2017-12-12 23:21 UTC
The Helpful Flowchart here https://www.dartlang.org/guides/get-started says `Get started with Fl` instead of `Get started with Flutter`.
![screenshot from 2017-12-12 15 21 16](https://user-images.githubusercontent.com/3357543/33913789-221eb532-df50-11e7-89e9-39d518bb1bea.png)

**Comment by chalin** [comment] 2017-12-13 12:36
Thanks for filing an issue. I confirm that I can see (only) "Fl" for the deploy of 2017/12/12 18:41 UTC.
The sources for that page have not changed in a while. I'm not seeing this problem locally.

I've redeployed. Can you confirm that the problem has gone away?

**Comment by chalin** [comment] 2017-12-13 12:51
@maryx, which browser and OS are you using?

@kwalrath, if I locally load [site-www/src/_guides/images/get-started-flowchart.svg](https://github.com/dart-lang/site-www/blob/master/src/_guides/images/get-started-flowchart.svg) in Chrome 62.0, and refresh a few times, I can make the "utter" of "Flutter" disappear!  Can you reproduce that too?

cc @kevmoo

**Comment by chalin** [comment] 2017-12-13 13:03
@kwalrath, @kevmoo - Actually, here is an even easier repro:

- Visit https://www.dartlang.org/guides/get-started.
- Scroll down to the flowchart.
- Right-click the flowchart and choose _Reload Frame_ a few times.

I see the Flutter word being truncated in the "Get started with Flutter" bubble.

**Comment by chalin** [comment] 2017-12-13 13:07
I cannot reproduce this problem in Safari, Firefox, nor Chromium.

**Comment by kwalrath** [comment] 2017-12-13 16:47
I can reproduce it in Canary (on Mac). Reloads seems to randomly switch between "Fl" and "Flutter".

**Comment by chalin** [comment] 2017-12-13 17:03
I've reported this over Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=794594

**Comment by maryx** [comment] 2017-12-13 18:04
@chalin I'm using Chrome with Linux. I also tried on Chrome on Mac.

**Comment by chalin** [comment] 2017-12-13 18:17
Which version(s) of Chrome? 
Thanks for confirming that it also fails under Linux.

**Comment by maryx** [comment] 2017-12-13 18:19
```
Google Chrome | 62.0.3202.94 (Official Build) (64-bit)
-- | --
Revision | 4fd852a98d66564c88736c017b0a0b0478e885ad-refs/branch-heads/3202@{#789}
OS | Linux
JavaScript | V8 6.2.414.42
Flash | 27.0.0.187 /usr/local/google/home/maryxia/.config/google-chrome/PepperFlash/27.0.0.187/libpepflashplayer.so
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Command Line | /usr/bin/google-chrome-stable --flag-switches-begin --flag-switches-end

```

**Comment by kwalrath** [comment] 2018-03-05 18:47
Closing because the flowchart is no more.

**Closed by kwalrath** 2018-03-05 18:47 UTC
Labels: P1
