### ISSUE TITLE
Dart site in Brave Browser doesn't open well

### ISSUE THREAD

**Issue by cronos88** [dart-lang/site-www#1838] opened 2019-08-18 04:18 UTC
S.O: Windows 10
Browser: Brave version 0.67.125

When I open dart site, doesn't show animation intro (Paint your UI to life) and in the Try Dart in your Borwser section, doesn't show console.

When I inspect the page, in Console appear the following error:

new_embed_dart.dart.js:449 Uncaught Error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at hX.ew (new_embed_dart.dart.js:9803)
    at ez.e2 (new_embed_dart.dart.js:8683)
    at Object.eval (eval at pw (new_embed_dart.dart.js:590), <anonymous>:3:36)
    at iM.$0 (new_embed_dart.dart.js:4987)
    at iL.$1 (new_embed_dart.dart.js:4995)
    at mL.d2 (new_embed_dart.dart.js:5814)
    at mO.$1 (new_embed_dart.dart.js:5851)
    at Object.rR (new_embed_dart.dart.js:1362)
    at Object.rS (new_embed_dart.dart.js:1353)
    at ez.fc (new_embed_dart.dart.js:8681)

I Attach some images.

thanks.
![Screenshot_1](https://user-images.githubusercontent.com/5728603/63220056-47062500-c145-11e9-834c-1af48886f6bd.png)
![Screenshot_2](https://user-images.githubusercontent.com/5728603/63220057-47062500-c145-11e9-8d9b-033f0fd6beb3.png)
![Screenshot_3](https://user-images.githubusercontent.com/5728603/63220058-47062500-c145-11e9-9060-98bff8e7f02e.png)

**Comment by domesticmouse** [comment] 2019-08-19 00:55
There are two separate problems here. First, Brave is preventing the video from auto-playing, which we should detect and deal with. You can enable the Paint your UI to life by toggling autoplay to on in the url bar.

The errors you see in the console are actually the DartPad embed at the bottom of the page failing. That is a more interesting problem. Oddly enough, our [test page](https://dartpad.dartlang.org/experimental/new_embeddings_demo.html) renders fine in Brave, but the embed on the main page doesn't. Assigning to @johnpryan to figure out what has gone wrong here.

Thanks for the report!

**Comment by johnpryan** [comment] 2019-08-19 16:32
This could be related to #1837

**Comment by kwalrath** [comment] 2019-09-10 18:42
Closing because this doesn't affect people who are willing to use another browser. If anyone is invested in making this work, we'd love your help.

**Closed by kwalrath** 2019-09-10 18:42 UTC
Labels: DartPad, p1-high

**Comment by domesticmouse** [comment] 2019-09-10 23:18
The issue is brave refuses to auto play videos.

**Comment by kwalrath** [comment] 2019-09-10 23:36
A possible solution would be to display a button or image if the browser doesn't autoplay videos.

**Comment by domesticmouse** [comment] 2019-09-11 11:46
I'm guessing the video tag has fallback content that we could display an image of the final state of the animation
