### ISSUE TITLE
'Dart SDK' choco installation confusing. Backed out.

### ISSUE THREAD

**Issue by seenickcode** [dart-lang/site-www#1073] opened 2018-08-11 12:16 UTC
Hey guys,

Just a heads up, the Windows `choco` installation of Dart, cited here: https://www.dartlang.org/tools/sdk, does not add any Dart tools to the path. Even if this is intended, **it is very difficult to find where exactly Dart tools are installed**. I had to remove Dart in the end because of this and use the normal .msi installer.

Little things like this, that can be easily fixed or clarified in the instructions hurts overall adoption.

**Comment by kwalrath** [comment] 2018-08-14 16:56
Thanks for letting us know, @seenickcode.

Can someone with Windows and chocolatey experience help us improve the instructions? The code is in another repo, actually: https://github.com/dart-lang/site-shared/blob/master/src/tools/sdk/_windows.md

/cc @kevmoo

**Comment by ruv** [comment] 2018-09-08 12:34
In my case Dart was installed via dependencies (on installing sass using choco), and it was installed automatically into `C:\tools\dart-sdk` directory. PATH variable in the registry was not updated.
Can the target directory be configured?

**Comment by idietmoran** [comment] 2018-10-02 01:30
I'm fairly certain there's something you could do in the Chocolatey script that should be fairly easy.

Maybe this.
https://github.com/chocolatey/choco/wiki/HelpersInstallChocolateyEnvironmentVariable

**Comment by strotech** [comment] 2018-10-26 04:05
i am a first time contributor and recently started learning about dart

Pardon me if i am wrong. I just tried out the installation from https://www.dartlang.org/tools/sdk and i did a refreshenv and i when i try dart from cli, i am able to see the dart documentation

I

**Comment by strotech** [comment] 2018-10-26 13:44
i would like to reproduce the issue.
Please provide the version of windows and the logs of installation if possible

**Comment by pmundt** [comment] 2019-06-08 10:26
A simple note as to the precise location of the default install directory (seemingly `tools\dart-sdk`) would be a useful addition to the documentation - indeed, Googling around for hints as to the install path is what brought me to this issue. On a `refreshenv` the PATH updates work as expected, but it still took a bit of digging around to figure out where, precisely, these were actually installed such that I could point the IntelliJ path at the appropriate SDK install location.

**Comment by rdnobrega** [comment] 2020-05-25 02:42
Hi, could you just tell us how to install it in another folder? Or update the site to do manual install by downloading sdk manually...

**Comment by kwalrath** [comment] 2020-05-26 15:26
There's a whole nother page about installing manually.

**Comment by rdnobrega** [comment] 2020-05-26 16:32
Well, losing control of what enters where in my computer is not what I expect to be a "novice" thing. Anyways, since you didn't point it anywhere, for anyone who got here for the same reason:
1. Download Dart and put the folder wherever you would like;
2. Add to PATH: "<dart directory>\bin".

**Comment by Adefebrian** [comment] 2020-09-24 23:13
if you are using linux u can install with ez way with command > for debian base : sudo apt-get install dart . for arch base : sudo pacman -S dart / yay dart. u dont need to set path after installing dart u can start to coding dart on ur editor or terminal .

**Comment by woinbo** [comment] 2021-01-08 03:56
You can add path your-self by editing environment variable in your operating system setting

STEPS TO ADD PATH: (In windows)

NOTE: make sure you have downloaded dart-SDK on your pc

STEP1: Press windows key then type env, you will see edit environment variable option, click and open it
STEP2: In the newly opened window you will find Path as variable select it and click on edit.
STEP3: Then add the path to your dart-sdk folder.
STEP4: press enter and click ok 2 times

That's how you add path.

Well, while installing using choco, choco should automatically add path in the env.

**Comment by mohitsaxenaknoldus** [comment] 2021-08-03 16:46
Please assign it to me. I will help you improve the instructions.

**Comment by kwalrath** [comment] 2021-08-03 17:44
> Please assign it to me. I will help you improve the instructions.

Great! I'm looking forward to seeing your improvements.

**Comment by mohitsaxenaknoldus** [comment] 2021-08-03 19:39
I've opened a PR for it: https://github.com/dart-lang/site-www/pull/3445
Please check.

**Closed** 2021-08-10 16:57 UTC
Labels: help wanted, InstallDart, beginner, needs-info
