### ISSUE TITLE
Document (current) best practices for platform-specific code (PSC)

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/site-www#1750] opened 2019-07-10 20:21 UTC
We have basic support for PSC, but it's not well documented and there are potentially big holes that a user could fall through.

- Document the recommended approach here
- Link to working examples (pkg:http, etc)
- Explain pitfalls (defining types, exports, etc)
- Hint at future direction?

**Comment by banalg** [comment] 2019-08-17 13:40
If I can just add my two cents on this topic. I'm currently developing some IoT stuff on a RaspberryPi with Dart. I usually test on my laptop where it isn't possible to use the physicals pins of the Raspberry Pi, so I developed a mocked library to simulate button press and on/off a led. But I currently need to manually switch the package import between the real and the mocked GPIO library.
I checked the http library and the control seems be done by checking the presence of these dart components : dart.library.html or dart.library.io.
But in my case, as both (Raspberry Pi and my laptop) use the dart.io library, which kind of control could I use ? Isit possible to check the operating system, or another things ?

**Comment by natebosch** [comment] 2019-08-19 17:02
> Is it possible to check the operating system, or another things ?

No, only the presence or absence of the `dart:` libraries. Imports based on arbitrary other information are not compatible with our approach for modular builds.

**Comment by escamoteur** [comment] 2019-10-01 13:03
@mit-mit Another application would be see here https://github.com/flutter/flutter/issues/30845 if someone want's to have different pages for iOS/Android but don't want to carry the code of the not used platform with it.

**Comment by mit-mit** [comment] 2019-11-13 09:57
Closing as a dupe of https://github.com/dart-lang/site-www/issues/1569, which has an active PR. If anything is missing there, please comment on the PR

**Closed** 2019-11-13 10:01 UTC
Labels: docs, e2-days, e3-weeks, enhancement, p2-medium
