### ISSUE TITLE
Typos in Iterable collections @ CodeLabs 

### ISSUE THREAD

**Issue by mabuthraa** [dart-lang/site-www#3206] opened 2021-05-05 22:13 UTC
Exercise: Filtering elements from a list
URL: https://dart.dev/codelabs/iterables#exercise-filtering-elements-from-a-list

Currently: 
Name of method filterUnder21.

Expecte:
Name of method filterAbove21.

Scope: 
Both exercise explanation and code

Issue: 
Request to return an Iterable containing all users of age 21 or more. So I think the name of the method is misleading with contrary meaning. It might to be filterAbove21.

Respects,'.

**Comment by parlough** [comment] 2021-05-06 01:57
Thanks for the report @mabuthraa, I appreciate you taking your time. There is a preexisting issue for this though, so I'll close this one in favor of the original. I'll work to get that issue fixed soon as well. Thanks again!

Duplicate of https://github.com/dart-lang/site-www/issues/3183

**Closed by parlough** 2021-05-06 01:57 UTC
