### ISSUE TITLE
Control flow collections 

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/site-www#4661] opened 2023-03-14 14:53 UTC
### What information is missing?

We might already cover this somewhere, just making this to check back once I have time...

I was reading about [maps](https://dart.dev/language/collections#maps) and at the end of the section it points to the [control flow collections proposal](https://github.com/dart-lang/language/blob/master/accepted/2.3/control-flow-collections/feature-specification.md), which was written in 2019. 

I very briefly searched the site to replace the link to point to something in dart.dev, but didn't find anything.

### How would you like us to fix this problem?

I think we should point to dart.dev for that topic.
1. does that content already exist in the site? where?
2. should we add it? what's worth saying about it?
3. where would that info go? (with control flow content, collections, etc?)

**Comment by parlough** [comment] 2023-03-14 17:53
We talk about these in the [Collection operators](https://dart.dev/language/collections#collection-operators) section, but it is something we've been tracking as needing to document better. For example, we don't even have an example of using `else` with a **collection if**.

It should likely go with collection content rather than control flow. I think an easier to understand name is "Collection operators" like we use in the above section or "Collection control flow" rather than "Control flow collections".

Closing as a duplicate of https://github.com/dart-lang/site-www/issues/2093

**Closed by parlough** 2023-03-14 17:53 UTC
Labels: new page/topic request
