### ISSUE TITLE
I declared a get property in extension, but appearing conflict when I am using this property in the extension declaration.

### ISSUE THREAD

**Issue by guolingege** [dart-lang/site-www#2520] opened 2020-07-13 06:38 UTC
Page URL: https://dart.dev/tools/diagnostic-messages.html
Page source: https://github.com/dart-lang/site-www/tree/master/src/tools/diagnostic-messages.md

Description of issue:
```
extension BuildContextEx on BuildContext {
  static Map<int, bool> _isLoadingMap = {};

  set isLoading(bool value) {
    _isLoadingMap[this.hashCode] = value;
  }

  bool get isLoading {
    return _isLoadingMap[this.hashCode] ?? false;
  }

 void someFunction() {
   this.isLoading;/// error appears here:[error: A member named 'isLoading' is defined in extensions 'BuildContextEx' and 'BuildContextEx' and neither is more specific. (ambiguous_extension_member_access at [msv_flutter] lib/extensions/BuildContextEx.dart:37)]
 }
}
```

I found an official doc points out that "A member named ‘{0}’ is defined in extensions ‘{1}’ and ‘{2}’ and neither is more specific", but the error in my project says the two extensions are same!

<img width="1332" alt="截屏2020-07-13 下午2 33 21" src="https://user-images.githubusercontent.com/13193905/87277914-dd89c480-c515-11ea-9bcb-527b22872569.png">

```
environment:
  sdk: ">=2.7.0 <3.0.0"
```
My dart sdk version is 2.8.4

**Comment by kwalrath** [comment] 2020-07-13 17:49
We need to figure out whether this is a doc bug or an SDK bug. @filiph?

**Comment by kwalrath** [comment] 2020-07-15 00:22
Maybe @bwilkerson can clarify?

**Comment by domesticmouse** [comment] 2020-07-16 05:36
@guolingege can you please supply a minimised reproduction case? 

I'm curious what the `BuildContextEx` is in that error message?

**Comment by bwilkerson** [comment] 2020-07-16 14:04
A minimal reproduction case would be very helpful. In the absence of that, I have a couple of questions that might also help.

Do you have another extension named `BuildContextEx` that defines those two members and is imported into `BuildContextEx.dart`?

Is the class `BuildContext` generic?

**Comment by guolingege** [comment] 2020-07-16 14:24
I will send you tomorrow

发自我的iPhone

**Comment by parlough** [comment] 2021-06-24 18:02
Hey @guolingege, just checking in to see if you were able to resolve your issue or if you had any extra information.

If you are still experiencing the issue, I recommend trying the latest version of Dart(https://dart.dev/get-dart) if possible as there have been lots of improvements to diagnostics since the 2.8.4 release :)

Thanks again!

**Comment by parlough** [comment] 2021-06-29 17:45
I'm going to close this issue for now, but if you are still experiencing this issue or another, always feel free to open another issue! Don't forget to try the latest version of Dart as well, thanks again!

**Closed by parlough** 2021-06-29 17:45 UTC
Labels: needs-info
