### ISSUE TITLE
Dart Codelab Sample shows XMLHttpRequest Error on line 1

### ISSUE THREAD

**Issue by bobjoyce** [dart-lang/site-www#2399] opened 2020-05-11 16:32 UTC
The Intro to Dart for Java Developers codelab Starting Shapes now shows an XMLHttpRequestError on line 1, even on the sample code.  This error did not occur 2 days ago (Saturday) on the same sample.  The error happens on both MacIntosh using Chrome (even after a restart) and on Windows.  

![image](https://user-images.githubusercontent.com/804093/81586231-11a40600-936a-11ea-9cf8-424ff589a6d6.png)

**Comment by domesticmouse** [comment] 2020-05-11 23:51
Duplicate of https://github.com/dart-lang/dart-pad/issues/1554. I believe this has been rectified by rolling restart of the backend compilation service

**Comment by bobjoyce** [comment] 2020-05-13 01:03
Thanks, Brett.  That fixed the issue yesterday, but the same or a similar
issue now appears to be happening again.  I filed another issue.

Bob

**Comment by domesticmouse** [comment] 2020-05-13 02:39
Yup, this is a still ongoing issue as I figure out how to keep the backend sane and serving.

**Comment by domesticmouse** [comment] 2020-05-15 04:27
I think this is now mitigated, mostly. I still have a few 500s, now and then, but nothing like earlier in the week. Closing this out.

**Closed by domesticmouse** 2020-05-15 04:27 UTC
Labels: DartPad, blocked, codelabs
