### ISSUE TITLE
`final` explanation from 'A Tour of the Dart Language' is a bit misleading

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/site-www#1203] opened 2018-10-22 23:33 UTC
Page URL: https://www.dartlang.org/guides/language/language-tour
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/language-tour.md

I think that the explanation for the `final` keyword from the Dart language tour is a bit misleading.  It states:

>You can’t change the value of a final variable:

While technically true, coming from a C++ background, my expectation was that `final` is similar to `const` in C++ where it is predominantly used with pointers and references to specify that the object cannot be (visibly) mutated via that pointer/reference. It would help if the Dart language tour explicitly mentioned that `final` does not prevent the object from being mutated.

(As an aside, I think that `final` makes cases like:
```dart
final x = foo();
bar(x); // Does this mutate x?
```
misleading to readers... Should we possibly consider discouraging that on one of the Effective Dart pages?)

**Comment by kwalrath** [comment] 2019-01-04 18:38
@munificent do you have an opinion on this?

**Comment by munificent** [comment] 2019-01-05 00:01
No, I don't think we should discourage using `final` for variables that refer to objects that can be internally mutated. It might be a little confusing to people whose mental model is `const` in C/C++, but it's the expected behavior for users coming from JS, Java, C#, Scala, Swift, Kotlin, etc. In all of those languages, it's understood that `let`/`final`/`const`/`readonly`/`val` is a property of the variable, not the object being referred to.

Also, we want people to use single-assignment variables because that makes code easier to maintain since it means at least some forms of mutation (reassignment) are being restricted.

**Comment by jamesderlin** [comment] 2019-01-05 04:41
1. I just want to make sure that everyone's clear that I'm really just asking that the language-tour page state that `final` does not disallow mutation, either explicitly or via an example.  I don't expect that request to be controversial.

2. Regarding `final` style (which I do expect to be controversial and don't really expect agreement or action on): yes, as a longtime C and C++ programmer, I find it weird.  The equivalent style in C or C++ would be:

   ```C
    void foo(const int x, const char* const s) {
        const int y = x * x;
        ...
    }
    ```

   and I think almost all C and C++ programmers would frown on such code.  The typical expectation among C and C++ developers is that `const` on the variable provides little benefit; for *local* variables (which should have limited scope), it should be mostly self-evident whether variables are reassigned, and if you don't want a variable to be reassigned, just don't do it.  It's not clear to me why disallowing reassignment with `final`/et. al. is preferable in Dart/JS/Java/etc.  Meanwhile, being able to easily specify that the object won't be mutated would provide a much clearer benefit.  Alas. =/

**Comment by jamesderlin** [comment] 2019-03-12 23:08
I just noticed that @munificent had similar questions about the utility of `final` for local variables in https://github.com/dart-lang/language/issues/136#issuecomment-451287523.

**Comment by munificent** [comment] 2019-03-14 21:05
The equivalent semantics in C/C++ is much closer to:

```c
void foo(char* const string) {
  string = "a different string";
  string[0] = 's';
}
```

Here, the first line is an error because the variable cannot be re-assigned. But the second line is perfectly fine as far as C is concerned. You're free to modify the object being referred to.

**Comment by jamesderlin** [comment] 2019-03-14 21:20
Yes. (Sorry, I meant that making a variable `final` in Dart is equivalent to changing an existing `const char*` variable in C to `const char* const`.)

My point remains that most C and C++ developers would discourage doing that for local variables or function parameters.

**Closed** 2020-10-20 15:33 UTC
Labels: LanguageTour, e0-minutes, p2-medium
