### ISSUE TITLE
'Understanding null safety' page issue

### ISSUE THREAD

**Issue by Dimibe** [dart-lang/site-www#2763] opened 2020-11-17 17:35 UTC
Page URL: https://dart.dev/null-safety/understanding-null-safety/
Page source: https://github.com/dart-lang/site-www/tree/master/src/null-safety/understanding-null-safety/index.md

Description of issue:
In the part [nullability-and-generics](https://dart.dev/null-safety/understanding-null-safety#nullability-and-generics) is the the following example: 

```dart
// Using null safety:
class Interval<T extends num?> {
  T min, max;

  bool get isEmpty {
    var localMin = min;
    var localMax = max;

    // No min or max means an open-ended interval.
    if (localMin == null || localMax == null) return false;
    return localMax <= localMin;
  }
}
```
and the after that the statement "Note we have no constructor this time, and that’s OK.". 

That's seems to be not true. I tried the example on my machine and the initialization for the fields is required, regardless if it's `<T extends num>` or `<T extends num?>`. 

Thats seems right to me because a few sentence later it is mentioned that " a nullable bound does not prevent users from instantiating the class with non-nullable types" which would lead to an exception if the fields are not initialized. So I think the documentation is wrong here.  

I'm currently using Flutter 1.24.0-8.0.pre.252, channel master and Dart 2.12.0 (build 2.12.0-45.0.dev).

**Comment by hankyusa** [comment] 2021-02-18 18:22
I'm having the same issue.

Paste the following into [DartPad with null safety enabled](https://dartpad.dartlang.org/?null_safety=true).

```dart
// Using null safety:
class Interval<T extends num?> {
  T min, max;

  bool get isEmpty {
    var localMin = min;
    var localMax = max;

    // No min or max means an open-ended interval.
    if (localMin == null || localMax == null) return false;
    return localMax <= localMin;
  }

  toString() => '($min, $max)';
}

void main() {
  final interval = Interval<int?>()
    ..min = -1
    ..max = 1;
  print(interval);
}

```

Click "RUN" button.

Console shows the following output.

```plain
Error compiling to JavaScript:
Warning: Interpreting this as package URI, 'package:dartpad_sample/main.dart'.
lib/main.dart:3:5:
Error: Field 'min' should be initialized because its type 'T' doesn't allow null.
  T min, max;
    ^^^
lib/main.dart:3:10:
Error: Field 'max' should be initialized because its type 'T' doesn't allow null.
  T min, max;
         ^^^
Error: Compilation failed.
```

**Comment by TahaTesser** [comment] 2021-08-31 11:19
Thre was new a duplicate of https://github.com/dart-lang/site-www/issues/3534, i filed an fix that makes `T` nullable but constructor is a better fix, waiting for PR to land and no more info is needed

**Closed** 2021-09-09 00:31 UTC
Labels: p2-medium, e0-minutes, null-safety
