### ISSUE TITLE
Improve site navigation and search

### ISSUE THREAD

**Issue by alecorsino** [dart-lang/site-www#1348] opened 2019-02-11 02:11 UTC
Page URL: https://www.dartlang.org/guides/language/language-tour
Page source: https://github.com/dart-lang/site-www/tree/master/src/_guides/language/language-tour.md

Description:
In the Built-in types section it would be important to add 'Set' as a type. I had to dig into Library Tour to find it, i was wondering if there was support for Sets and the Tour kinda doesn't tell me much about that section.
Also I find the left navigation menu is somehow not intuitive to get to different important sections like Dart DSK

**Comment by kwalrath** [comment] 2019-02-11 16:48
The first part is a duplicate of #1257. I'd close this, if not for the second part...

I'm working on the left nav right now, so I'd love to know what specifically you'd like to see. (And what do you mean by DSK?)

We expect to have a deeper nav structure, a la flutter.io, so we can include more pages in the left nav. The trick is making things findable within that deep structure.

**Comment by alecorsino** [comment] 2019-02-12 01:28
sorry, I meant SDK.

To give you few examples:
Rust lang "The Book" is good way to learn from nothing to advanced about the language.
Kotlin lang is another good example of structure and the search functionality is also good in my opinion.

Sorry but i have to say I really dislike the search functionality Dart website has; Google's Custom search engine for website it's just not good. I'd expect just search only documentation in the website itself only.

Just take a look at Rust and Kotlin they have good functional websites.
Anyways great work and thank you for the hard work and all the effort you guy put to make such a nice language

**Comment by kwalrath** [comment] 2019-02-12 01:41
Thanks for the details, @alecorsino. I agree that our search isn't ideal, so it's good that you gave us pointers to sites whose search you like

**Comment by atsansone** [comment] 2023-04-04 21:52
Sets were modified along with other pages in the rearrangement of the Language Tour (https://github.com/dart-lang/site-www/pull/4656).

**Closed by atsansone** 2023-04-04 21:52 UTC
Labels: p2-medium, e2-days, e3-weeks
