### ISSUE TITLE
console text in DartPad's dark theme isn't readable

### ISSUE THREAD

**Issue by ryanmcginnis** [dart-lang/site-www#2209] opened 2020-01-10 23:41 UTC
Page URL: https://dart.dev/codelabs/iterables#exercise-practice-writing-a-test-predicate
Page source: https://github.com/dart-lang/site-www/tree/master/src/codelabs/iterables.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

when i run the DartPad in the section of the linked page, i can't easily read the text:

![image](https://user-images.githubusercontent.com/13040933/72193672-5b321380-33bf-11ea-867c-d9bb5ed467ab.png)

i tested in Chrome 79.0.3945.117 and Safari 13.0.4 (14608.4.9.1.4).

**Comment by kwalrath** [comment] 2020-01-10 23:56
Closing as a duplicate of https://github.com/dart-lang/dart-pad/issues/1424.

**Closed by kwalrath** 2020-01-10 23:56 UTC
Labels: DartPad
