### ISSUE TITLE
Fix variable initialization in Java Dart Codelab

### ISSUE THREAD

**Issue by mojjammil** [dart-lang/site-www#2698] opened 2020-10-11 13:14 UTC
The part where we Initialize _speed to 0:

It is confusing not knowing exactly where to initialize? Within the class or inside main, or outside?

**Comment by sumandipanshu** [comment] 2020-10-11 18:18
>The part where we Initialize _speed to 0:

@mojjammil Could you please provide any reference to where you are getting confused?

**Comment by mojjammil** [comment] 2020-10-12 07:37
It's in Intro to Dart for Java Developers -> Create a simple Dart class -> Add a read-only variable - > Initialize _speed to 0:

Mentioning it needs to be declared within the class might be handier

**Comment by sumandipanshu** [comment] 2020-10-12 20:40
>Mentioning it needs to be declared within the class might be handier

Dart implements privacy at library level, not the class level (unlike Java).
So, placing it anywhere inside the same library would make no difference.
[Refer here.](https://dart.dev/guides/language/language-tour#libraries-and-visibility)

Duplicate of #1463

**Comment by kwalrath** [comment] 2020-10-12 23:33
@sumandipanshu #1463 doesn't seem to be related. Was there another bug you meant to refer to?

**Comment by sumandipanshu** [comment] 2020-10-13 13:45
@kwalrath Ahh, sorry i mistakenly linked it to the another issue.
This is the [issue](https://github.com/dart-lang/dart-pad/issues/1463) which i wanted to link, but it seems to be in a different repository.

**Comment by kwalrath** [comment] 2020-10-19 23:39
I understand now. We could be clearer about what we mean.

**Comment by sumandipanshu** [comment] 2020-10-20 16:43
I would like to work on this issue. But I'm confused about what needs to be done in order to resolve this issue? what kind of info we need to add there? 
And where is the source code?

**Comment by kwalrath** [comment] 2020-10-20 17:24
@sumandipanshu unfortunately this codelab isn't open source, so a Googler has to fix it. :(

**Comment by parlough** [comment] 2023-05-31 21:16
Thanks for the issue!

This codelab has been retired in favor of other learning material which we are working on improving and expanding, as the codelab was not up to date with modern Dart. We will be releasing more learning material over time, and for now, have a bunch of samples at https://dart.dev/language and a detailed walkthrough of different Dart features, that is written in a way that should be familiar to Java developers. 

Thanks again!

**Closed by parlough** 2023-05-31 21:16 UTC
Labels: p2-medium, codelabs, e0-minutes, ltw-triage
