### ISSUE TITLE
Code sample needs format/description improvements

### ISSUE THREAD

**Issue by emilieroberts** [dart-lang/site-www#2790] opened 2020-12-06 12:06 UTC
The code sample for [Do Annotate When Dart Infers The Wrong Type](https://dart.dev/guides/language/effective-dart/design#do-annotate-when-dart-infers-the-wrong-type) has the same code sample twice, once with green "do", and the second with grey. It follows a long list of green "dos" and red "don'ts" so it is confusing because the code is identical.

![Screenshot 2020-12-06 at 1 05 50 PM](https://user-images.githubusercontent.com/8290920/101279633-d2d11400-37c3-11eb-90d3-167922af41fb.png)

**Comment by Abhishek01039** [comment] 2020-12-08 04:35
@emilieroberts 
Please see
``` num highest = 0;```
 and ```var highest = 0;```
It is different in both examples.


Thanks

**Comment by emilieroberts** [comment] 2020-12-08 10:48
Wow, ok, that is really not clear. Maybe this could be improved in the
following ways:
- fix the box formatting so it says "don't" and is red like the other code
samples
- mention in the proceeding paragraph what the dev is supposed to be
looking for, eg. "notice the type of the variable 'highest' in the
following sample"
- and/or use colour to highlight the important line or "var/num"
declaration that is different.

Il mar 8 dic 2020, 05:35 Abhishek Ghaskata <notifications@github.com> ha
scritto:

**Comment by munificent** [comment] 2020-12-16 23:29
Duplicate of #2132.

**Closed by munificent** 2020-12-16 23:29 UTC
Labels: EffectiveDart, e0-minutes, p2-medium
