### ISSUE TITLE
Bad URL

### ISSUE THREAD

**Issue by tijoforyou** [dart-lang/site-www#1621] opened 2019-05-15 11:25 UTC
URL: https://dart.dev/articles/event-loop
Expected page: The awesome article on "The Event Loop and Dart".

https://www.dartlang.org/articles/event-loop/ used to work in the past, before the redirect to https://dart.dev

There is a reference to this article from https://api.dartlang.org/stable/2.3.0/dart-async/scheduleMicrotask.html

**Comment by eldraco19** [comment] 2019-05-22 15:37
Hey I found the article on web archive .
https://web.archive.org/web/20170704074724/https://webdev.dartlang.org/articles/performance/event-loop

How can I contribute to this issue ? Please guide me .

**Comment by kwalrath** [comment] 2019-05-22 17:48
It's probably easiest for me to fix it. The question is whether I should add the article back or redirect to archive.org. The former might be better, from an analytics POV, so we can track how many people are looking at the article.

**Comment by kwalrath** [comment] 2019-05-22 20:20
Dupe of #1617.

**Closed by kwalrath** 2019-05-22 20:20 UTC
Labels: bad URL, e0-minutes, p2-medium
