### ISSUE TITLE
iOS safari page horizontal size issue

### ISSUE THREAD

**Issue by sarasotafingerprints** [dart-lang/site-www#5062] opened 2023-07-14 07:40 UTC
### Page URL

https://dart.dev/language/operators

### Describe the problem

The page is too wide on mobile on iPhone 12 pro

### Expected fix

Fix css width. See screenshot:

![IMG_0128](https://github.com/dart-lang/site-www/assets/121450556/0e709ab3-9691-490f-aa8d-cf7d4e9caef4)

**Comment by danagbemava-nc** [comment] 2023-07-14 11:44
This is caused by the table on the page

**Comment by danagbemava-nc** [comment] 2023-07-14 11:47
Closing this as a duplicate of #5041

**Closed by danagbemava-nc** 2023-07-14 11:47 UTC
Labels: language, p2-medium, design, e1-hours
