### ISSUE TITLE
[PAGE ISSUE]: 'Understanding null safety'

### ISSUE THREAD

**Issue by jiqimao3528** [dart-lang/site-www#3534] opened 2021-08-31 09:57 UTC
### Page URL

https://dart.dev/null-safety/understanding-null-safety/

### Page source

https://github.com/dart-lang/site-www/tree/master/src/null-safety/understanding-null-safety/index.md

### Describe the problem

the code example in this page can not compile success:
```
class Interval<T extends num?> {
  T min, max;

  bool get isEmpty {
    var localMin = min;
    var localMax = max;

    // No min or max means an open-ended interval.
    if (localMin == null || localMax == null) return false;
    return localMax <= localMin;
  }
}
```

### Additional context

environment:
  sdk: '>=2.12.0 <3.0.0'

**Comment by TahaTesser** [comment] 2021-08-31 11:11
Hi @jiqimao3528 
It fails to compile because `T` is not nullable

Thanks for filing the issue

**Comment by TahaTesser** [comment] 2021-08-31 11:17
duplicate of https://github.com/dart-lang/site-www/issues/2763

**Closed by TahaTesser** 2021-08-31 11:17 UTC
Labels: p2-medium, e0-minutes, null-safety
