### ISSUE TITLE
Regression in docs for the event loop

### ISSUE THREAD

**Issue by natebosch** [dart-lang/site-www#2163] opened 2019-12-10 23:32 UTC
If I search for "Dart microtask" one of the first links is: http://www.dartlang.org/articles/event-loop/ 

That link redirects me to a medium article with is less useful than the old article. It doesn't mention "microtask" anywhere.

Do we have a plan to improve our documentation here? The codelab on async await (https://dart.dev/codelabs/async-await) doesn't mention "microtask" either. Understanding the difference between an event and a microtask is critical for reasoning about async code behavior and performance.

**Comment by kwalrath** [comment] 2019-12-11 02:38
Yep, we should do this, but I'm closing this as a duplicate of #2142.

(As for a plan... let's talk.)

**Closed by kwalrath** 2019-12-11 02:38 UTC
