### ISSUE TITLE
[PAGE ISSUE]: 'Fixing common type problems'

### ISSUE THREAD

**Issue by WissamALSbenaty** [dart-lang/site-www#5314] opened 2023-11-03 07:22 UTC
### Page URL

https://dart.dev/guides/language/sound-problems.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/guides/language/sound-problems.md

### Describe the problem

 Map<String,double> testMap ={
      "price": 1.5,
    };
    double? x= testMap[1];
    
    it shows me The argument type 'int' isn't related to 'String' and a small hint at testMap[1]

### Expected fix

shows a compile error at  testMap[1] to make sure that the provided type is subtype of string

### I would like to fix this problem.

- [ ] I will try and fix this problem on dart.dev.

**Comment by danagbemava-nc** [comment] 2023-11-03 12:11
Hi @WissamALSbenaty, you have defined a Map with a String key so you can only access the values using a string. 

This is working as intended. 

Closing from here as this is not a page issue.

Thank you

**Closed by danagbemava-nc** 2023-11-03 12:11 UTC
Labels: st.triage.triage-team, from.page-issue

**Comment by eernstg** [comment] 2023-11-03 14:18
@WissamALSbenaty, you might want to consider the following:

It is indeed working as intended when you don't get a compile-time error at the expression where operator `[]` is used on a `Map`, and the given key has a "wrong" type. This particular property of the design of the Dart collections has been questioned many times, but it was chosen deliberately, and it isn't likely to be changed.

Here is one reason why you would want to have this property:

```dart
class FakeMap1<K> implements Map<K, int> {
  noSuchMethod(_) => throw 'Not Implemented';
  int operator [](Object? _) => 42;
}

class FakeMap2<K> implements Map<K, int> {
  noSuchMethod(_) => throw 'Not Implemented';
  int operator[](covariant K _) => 42; // Let's true to use the actual key type!
}

void main() {
  Map<Object, int> map;
  map = FakeMap1<String>();
  print(map[10]); // '42'.
  map = FakeMap2<String>();
  print(map[10]); // Throws.
}
```

In this example, we're declaring two different kinds of fake maps, `FakeMap1` and `FakeMap2`, just so we can experiment with the two obvious candidate signatures for the index operator `[]`: We could use the parameter type `Object?` (which is what the actual `Map` classes do), or we could use the key type `K` (which is what is often requested by anyone who experienced the behavior that you describe).

The point is that it is OK to access a `Map` with key and value type `K` and `V`, respectively, using a supertype `Map<K2, V2>` rather than the more precise type `Map<K, V>`, as long as `K` is a subtype of `K2` and `V` is a subtype of `V2`. In the example we're working on an object which is actually a `Map<String, int>` (more precisely: it's a `FakeMap1<String>`, but that's a subtype of `Map<String, int>`), but we are using the static type `Map<Object, int>`.

The static type justifies a lookup like `map[10]`, because `10` is an object which is typable as `Object`. We're asking for the value corresponding to a key `10`, and the behavior of the map is well-defined when we're asking for a key that doesn't exist (a real map returns null, the fake map just returns the same value no matter what key we're asking for).

However, if we use the parameter type `K`, as in `FakeMap2`, then the lookup will fail with a run-time type error.

It's not wrong to say that "we didn't find it" when we're looking up the key `10` in a map whose key type is `String`, and saying "not found" seems more useful than raising a run-time type error. Hence, the parameter type `Object?` is considered more useful than the parameter type `K`.

The other side of that coin is what you described: The request for a lookup with a key whose type has nothing to do with the statically known key type looks like a bug, and it seems reasonable to expect a compile-time error.

However, it isn't going to be an error, because the actual parameter type is `Object?`, and that parameter type ensures that nothing is rejected, we can look up any key whatsoever, of any type.

The situation can still be detected, of course, and we're using a lint to do that: [`collection_methods_unrelated_type`](https://dart.dev/tools/linter-rules/collection_methods_unrelated_type).

So you might well want to enable that lint by putting the following into your `analysis_options.yaml` file:

```yaml
linter:
  rules:
    - collection_methods_unrelated_type
```

When that lint rule is enabled, we get a diagnostic message at the lookup `testMap[1]` in the original example.

**Comment by WissamALSbenaty** [comment] 2023-11-03 14:59
@eernstg 
Oh thanks a lot ! That is what i was searching for !

I have tried to find the appropriate rule in linter but i couldnt find it
