### ISSUE TITLE
Pubspec includes two dependency overrides pointed at external repos

### ISSUE THREAD

**Issue by RedBrogdon** [dart-lang/site-www#1757] opened 2019-07-11 22:01 UTC
The site's pubspec:

https://github.com/dart-lang/site-www/blob/master/pubspec.yaml

Includes two dependency overrides that point to @chalin's personal GitHub account:

```yaml
dependency_overrides:
  code_excerpt_updater:
    git: https://github.com/chalin/code_excerpt_updater.git
    # path: ../code_excerpt_updater
  code_excerpter:
    git: https://github.com/chalin/code_excerpter.git
    # path: ../code_excerpter
```

While the repos are unlikely to be taken down, it'd be good to remove those overrides or point them to copies in a more official location.

**Comment by legalcodes** [comment] 2019-08-06 20:23
+1, may or may not be involved in https://github.com/dart-lang/site-www/issues/1818

**Comment by chalin** [comment] 2019-08-06 21:30
> While the repos are unlikely to be taken down

FWIW: you are right that I won't be taking those down.

> may or may not be involved in #1818

Unsure what kind of causal link you see with the use of dependency overrides, but I don't believe that would be the root cause of #1818.

**Comment by kwalrath** [comment] 2019-08-06 23:03
Not your fault! It looks like it was caused by an extra file in the latest release of the crypto package.

**Comment by chalin** [comment] 2019-08-07 12:50
👍

**Comment by dnfield** [comment] 2020-03-17 06:03
There are a few problems with this.. 

1. If you try to run checks on older versions of the repository, the versions of the tools are not versioned with the code, and may not be compatible.
2. If changes are made upstream that are incompatible, you may not find out until you go to push an unrelated commit to the source repository.

We should ideally publish these packages to pub and just be able to depend on them from there - that way it's clear what revision of the repo depended on what version of the tool(s).

I'm also trying to better understand some of the complexity in these tools, and whether we're doing work that jekyll could just be doing for us (perhaps via a plugin).

**Comment by dnfield** [comment] 2020-03-17 06:03
@chalin do you plan to publish these to pub?

**Comment by chalin** [comment] 2020-03-17 14:37
> @chalin do you plan to publish these to pub?

 Yes, I'll get these published.

> There are a few problems with this... 1. If you try to run checks on older versions of the repository, the versions of the tools are not versioned with the code, and may not be compatible.

FYI: It was decided a while ago that we wouldn't put effort into maintaining older versions of the site (@kwalrath and @mit-mit can confirm).

> I'm also trying to better understand some of the complexity in these tools, and whether we're doing work that jekyll could just be doing for us (perhaps via a plugin).

Essentially, we used to have code-excerpt handling via a Jekyll plugin back in the AngularTS/Dart days, and the bottom line is that it made site generation slower; most writers find Jekyll too slow already. Writers rightfully expect a quick refresh cycle when working on a page. Prose edits are much more frequent than code excerpt changes. That is why code excerpt refresh was pulled out of the Jekyll site refresh loop. (To be clear, even back then, the code excerpter was run separately. In-page embedding of code excerpts was handled at site generation time, from the cached excerpts.)

Regarding the complexity of the tools. These tools evolved over time, addressing changing feature sets -- e.g., the tools can handle code-excerpt refresh in API docs (i.e., in API docs comments in code). This isn't a feature that we're using anymore AFAIK.

**Comment by dnfield** [comment] 2020-03-17 16:07
Thanks for the context!

We don't necessarily need this for multiple versions of the site, but we do need it if we want to be able to test previous commits - e.g. the last commit succeeded, this one failed, is it the version of package X impacting it?

**Comment by parlough** [comment] 2021-07-19 03:40
I'm going to close this as fixed by https://github.com/dart-lang/site-www/pull/3218 which changes these dependencies to use a direct path to the checked in versions within `site-shared` which is a managed Git submodule that must be updated explicitly.

**Closed by parlough** 2021-07-19 03:40 UTC
Labels: e1-hours, infrastructure, p2-medium
