### ISSUE TITLE
the old page has been redirect to a dangerous site; you can remove the prompt 

### ISSUE THREAD

**Issue by yao8384** [dart-lang/site-www#1831] opened 2019-08-10 02:00 UTC

**Comment by yao8384** [comment] 2019-08-10 02:02
[http://www.dartlang.cc](url)

**Comment by kwalrath** [comment] 2019-08-12 15:48
To my knowledge, we don't control or link to dartlang.cc. I'll see if there's something else we can do about this site.

**Comment by kwalrath** [comment] 2019-11-14 18:56
Closing because I've confirmed that dart.dev doesn't link to dartlang.cc.

/cc @messi01

**Closed by kwalrath** 2019-11-14 18:56 UTC
Labels: needs-info
