### ISSUE TITLE
404 not found error for example hyperlink.

### ISSUE THREAD

**Issue by boduan402** [dart-lang/site-www#2287] opened 2020-02-26 06:42 UTC
In this line:
You can also call an instance of a Dart class as if it were a function, as in `this example`.

The hyperlink of `this example` gives 404 error

**Comment by kwalrath** [comment] 2020-02-26 22:49
Closing as a duplicate of #2280. Thanks for making sure we know about this!

**Closed by kwalrath** 2020-02-26 22:49 UTC
