### ISSUE TITLE
[PAGE ISSUE]: 'Package dependencies'

### ISSUE THREAD

**Issue by wcarmon** [dart-lang/site-www#4219] opened 2022-09-13 13:46 UTC
### Page URL

https://dart.dev/tools/pub/dependencies.html

### Page source

https://github.com/dart-lang/site-www/tree/main/src/tools/pub/dependencies.md

### Describe the problem

example for caret syntax is unclear.  Does it stay within the same major version or the same minor version.

See https://dart.dev/tools/pub/dependencies#caret-syntax

Specifically this sentence: `For example, ^1.2.3 is equivalent to '>=1.2.3 <2.0.0', and ^0.1.2 is equivalent to '>=0.1.2 <0.2.0'. The following is an example of caret syntax:`

### Expected fix

... ^0.1.2 is equivalent to '>=0.1.2 <1.0.0' (assuming caret means retain major version only)

or 

... ^1.2.3 is equivalent to '>=1.2.3 <1.3.0'  (assuming caret means retain major & minor version)

**Comment by danagbemava-nc** [comment] 2022-09-13 14:55
I believe this is a duplicate of https://github.com/dart-lang/site-www/issues/4160 as such I'll be closing this in favor of https://github.com/dart-lang/site-www/issues/4160.

**Closed by danagbemava-nc** 2022-09-13 14:55 UTC
Labels: in triage
