### ISSUE TITLE
customize the PR template for this repo?

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/site-www#4916] opened 2023-05-23 20:26 UTC
We now have a PR template for the dart-lang/ repos (https://github.com/dart-lang/.github/blob/main/PULL_REQUEST_TEMPLATE.md). It helps set expectations for PRs - testing, discussions, updating changelog entries, ...

Any repo which does not explicitly override that default template will inherit the top-level template (which is fine - most of our repos have similar workflows and expectations). For the SDK repo, we did override it - it has a fairly different workflow; https://github.com/dart-lang/sdk/blob/main/.github/PULL_REQUEST_TEMPLATE.md.

You might consider overridding the PR template for this repo as well - I suspect the workflow for PRs here is pretty different from our other repos? In order to override you'd create a `PULL_REQUEST_TEMPLATE.md` in the `.github` dir.

**Comment by parlough** [comment] 2023-05-23 20:27
I'm going to close this as a duplicate of https://github.com/dart-lang/site-www/issues/4862.

It's on my to-do list for this week :)

**Closed by parlough** 2023-05-23 20:27 UTC
