### ISSUE TITLE
In the Dart tutorial, it states you can use an argument list, but when you try it, it won't compile

### ISSUE THREAD

**Issue by eladkatz** [dart-lang/site-www#1666] opened 2019-06-05 18:53 UTC
In "Intro to Dart for Java Developers", Section "2. Create a simple Dart class", it states:

> Dart's main method is named main() or (if you need access to command line arguments) main(List<String> args).

However, when I do that in DartPad, I get the following exception:
Uncaught exception:

> TypeError: Instance of 'JSArray': type 'JSArray' is not a subtype of type 'List<String>'

When attempting to run

**Comment by kwalrath** [comment] 2019-06-05 20:14
I don't see that exception when I change `()` to `(List args)` in https://dartpad.dartlang.org/f176b4c31b4be8a454107d0946fe2fa3.

Can you give me a way to reproduce the error you're seeing?

**Comment by kwalrath** [comment] 2019-08-08 17:44
Closing due to inability to reproduce the issue.

**Closed by kwalrath** 2019-08-08 17:44 UTC
Labels: needs-info
