### ISSUE TITLE
Document "replaced-by" when marking a package "discontinued"

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/site-www#4782] opened 2023-04-25 13:16 UTC
When a package has been marked "discontinued" in the admin tab on pub.dev it is possible to list a "replaced-by" package, example:
![image](https://user-images.githubusercontent.com/149732/234287269-d14ed998-3b4b-4f11-87cc-d5268ab47901.png)

We should probably mention that here:
https://dart.dev/tools/pub/publishing#discontinue

It might also be nice to show that anyone using a _discontinued_ package will be notified with messages like this:

```console
$ dart pub get
Resolving dependencies... (1.2s)
  my_old_pkg 1.2.0 (discontinued replaced by better_package)
Got dependencies!
```

Essentially, using "discontinued" and "replaced-by" will inform command-line users that a new "better_package" is available.

**Comment by parlough** [comment] 2023-04-27 21:14
Duplicate of https://github.com/dart-lang/site-www/issues/3750

**Closed by parlough** 2023-04-27 21:14 UTC
Labels: p3-low, e1-hours, packages
