### ISSUE TITLE
Remove embedded DartPads

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-www#422] opened 2017-11-09 14:17 UTC
Known affected pages:
- https://www.dartlang.org/guides/get-started
- https://www.dartlang.org/guides/language/language-tour
- https://www.dartlang.org/tutorials/language/futures
- https://www.dartlang.org/tutorials/language/streams

There may be more.

Chrome warnings as seen in the developer console:
- [Deprecation] Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
- [Deprecation] /deep/ combinator is no longer supported in CSS dynamic profile. It is now effectively no-op, acting as if it were a descendant combinator. You should consider to remove it. See https://www.chromestatus.com/features/4964279606312960 for more details.
- Blink deferred a task in order to make scrolling smoother. Your timer and network tasks should take less than 50ms to run to avoid this. Please see https://developers.google.com/web/tools/chrome-devtools/profile/evaluate-performance/rail and https://crbug.com/574343#c40 for more information.

**Comment by kwalrath** [comment] 2017-11-09 18:53
Is this caused by DartPad?

**Comment by chalin** [comment] 2017-11-09 20:02
Ah yes, that could very well be it!

**Comment by kwalrath** [comment] 2017-11-10 21:44
I don't see the Blink warning when I view those pages in Chrome Canary: Version 64.0.3261.0 (Official Build) canary (64-bit).

**Comment by kwalrath** [comment] 2018-03-05 18:56
DartPad's version of Polymer has been updated, but there are now **4** warnings in in https://www.dartlang.org/guides/get-started:

* [Deprecation] Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M67, around May 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
* imports.html:11890 This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead
* imports.html:12193 This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead
* [Deprecation] /deep/ combinator is no longer supported in CSS dynamic profile.It is now effectively no-op, acting as if it were a descendant combinator. /deep/ combinator will be removed, and will be invalid at M65. You should remove it. See https://www.chromestatus.com/features/4964279606312960 for more details.

For more info, see https://github.com/dart-lang/dart-pad/issues/791.

**Comment by kwalrath** [comment] 2019-01-30 21:22
Waiting to figure out what our DartPad strategy will be.

/cc @RedBrogdon

**Comment by kwalrath** [comment] 2019-08-08 17:41
#1799 switches us to the new DartPad, which causes no console warnings, yay!

**Closed by kwalrath** 2019-08-08 17:41 UTC
Labels: blocked, design, docs, e2-days, infrastructure, p2-medium
