### ISSUE TITLE
[PAGE ISSUE]: 'Add elements to the DOM'

### ISSUE THREAD

**Issue by asifimtiazahmed** [dart-lang/site-www#3514] opened 2021-08-23 04:07 UTC
### Page URL

https://dart.dev/tutorials/web/low-level-html/add-elements

### Page source

https://github.com/dart-lang/site-www/tree/master/src/_tutorials/web/low-level-html/add-elements.md

### Describe the problem

I am using the latest stable channel of flutter+dart. However I was trying out dart web, and The example here is outdated, not null safe, and frustrating! Please fix it, I want to be able to input a value in the HTML file and get that value in the main.dart file.

**Comment by parlough** [comment] 2021-08-23 16:31
Hey @asifimtiazahmed, thanks so much for opening an issue. This is one of the remaining pages we haven't had a chance to update yet, but it is on my to-do list and I'll start work on it soon.

I'm going to close this as a duplicate of https://github.com/dart-lang/site-www/issues/3415 since we're tracking the work there. If you have any more feedback on this issue, feel free to add it there, and if anyone wants to help with this migration, I'd be happy to help.

Sorry again about the delay in this migration. I appreciate the reminder to finalize that work :)

**Closed by parlough** 2021-08-23 16:31 UTC
Labels: duplicate
